backend/config/routes.rb
Rails.application.routes.draw do

  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable,
  # :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  # devise_for :users
  devise_for :users,  defaults: { format: :json }, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }


  resources :items, only: %i[index show]do
    post 'add_to_cart', to: 'items#add_to_cart'
  end
  root to: "items#index"


  resources :carts, only: %i[index] do
    # resources :cart_items, only: [] do
        patch 'update', on: :member  # Increment or decrement item count
        delete 'remove', on: :member  # Remove item from the cart
    # end
  end
  get 'carts/', to: 'carts#index'
  delete 'carts/', to: 'carts#destroy'
    
end

backend/app/models/item.rb
class Item < ApplicationRecord
  include Notifications

  has_rich_text :description
  has_one_attached :featured_image
  has_many :subscribers, dependent: :destroy
  after_update :update_log

  has_many :cart_items
  has_many :carts, through: :cart_items
  # belongs_to :cart_items, optional: false

  validates :name, presence: true
  validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than: 0 }

  def update_log
    puts "####################################"
    puts "#{self.name} is updated"
    puts "####################################"
  end
end

backend/app/models/item/notifications.rb
module Item::Notifications
  extend ActiveSupport::Concern

  included do
    has_many :subscribers, dependent: :destroy
    after_update_commit :notify_subscribers, if: :back_in_stock?
  end

  def back_in_stock?
    inventory_count_previously_was == 0 && inventory_count > 0
  end

  def notify_subscribers
    subscribers.each do |subscriber|
      ItemMailer.with(item: self, subsciber: subscriber).in_stock.deliver_later
    end
  end
end

backend/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_with_token!, only: %i[add_to_cart]

  before_action :get_item, only: %i[show update destroy]
  before_action :get_item_for_cart, only: %i[add_to_cart]
  before_action :get_cart, only: %i[add_to_cart]

  # GET /items
  def index
    @items = Item.all.order(rating: :desc)
    render json: { data: @items }, status: :ok
  end

  # GET /items/:id
  def show
    render json: { data: @item}, status: :ok
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    if @item.save
      render json: { data: @item }, status: :created
    else
      render json: { errors: @item.errors.messages }, status: :unprocessable_entity
    end
  end

  # PATCH /items/:id
  def update
    if @item.update(item_params)
      render json: { data: @item }, status: :ok
    else
      render json: { errors: @item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /items/:id
  def destroy
    @item.destroy
    head :no_content
  end

  def add_to_cart
    @cart_item = @cart.cart_items.find_by(item_id: @item.id)
    if @cart_item.nil?
      @cart_item = @cart.cart_items.create(item: @item) 
      # @cart_item.subtotal = @cart_item.item_count * @item.price
      # @cart_item.increment!(:item_count)
      # render json: { message: 'Item added to cart', item: @cart_item }, status: :created
    end
    @cart_item.subtotal = @cart_item.item_count * @item.price
    @cart_item.increment!(:item_count)
    render json: { message: "Item added to cart", item: @cart_item }, status: :created
    # else
    #   render json: { message: 'Item already added to cart', item: @cart_item }, status: :created
    # end
  end

  private

  # Strong parameters for creating and updating items
  def item_params
    params.expect(item: %i[ :name ])
  end

  # Find the item by its ID
  
  def get_item
    @item = Item.find_by(id: params[:id] )
    render json: { error: 'Item not found' }, status: :not_found if @item.nil?
  end
  
  def get_item_for_cart
    @item = Item.find_by(id: params[:item_id])
    render json: { error: 'Item not found' }, status: :not_found if @item.nil?
  end

  def get_cart
    # @cart = Cart.find_or_create_by(id: 6)
    puts "$Current user: #{current_user.id}, cart_id : #{current_user.carts}"
    @cart = current_user.carts

    if @cart.nil?
      render json: { error: "Cart not found for user_id: #{current_user.id}" }, status: :not_found 
    end
  end
end

backend/app/helpers/items_helper.rb
module ItemsHelper
end

backend/app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
<div style="margin: 40px; display: flex; flex-direction: column; gap: 10px;">
    <%= form.label :name%>
    <%= form.text_field :name%>
    <%= form.label :price%>
    <%= form.text_field :price%>
    <%= form.label :inventory_count %>
    <%= form.text_field :inventory_count%>
    <%= form.label :description%>
    <%= form.rich_text_area :description, style: "display: block"%>
    <%= form.label :featured_image %>
    <%= form.file_field :featured_image, style: "display: block; width: 400 px", accept: "image/*"%>
    <%= form.label :rating%>
    <%= form.text_field :rating%>
</div>
<div class="buttons" style="margin: 40px">
    <%= form.submit %>
</div>
<div class="buttons" style="margin: 40px">
    <%= link_to "Cancel", item %>
</div>
<% end %>

backend/app/views/items/_inventory.html.erb
<% if item.inventory_count? %>
    <p><%= item.inventory_count %>  in stock </p>
    <%= button_to "Buy Now", item, method: :buy_now%>
    <%= button_to "Add to cart", item, method: :add_to_cart%>
<% else %>
    <p> Out of Stock :( </p>
    <p> Subscribe to receive notification when Available </p>
    <%= form_with model: [item, Subscriber.new] do |form| %>
        <%= form.email_field :email, placeholder: "you@example.com" , required: true %>
        <%= form.submit "Subscribe" %>
    <%end%>
<% end %>

backend/app/views/items/edit.html.erb
<h1> Editing <%= @item.name %> </h2>
<%= render "form", item: @item %>

backend/app/views/items/index.html.erb
<h2 style="text-align: center;">Featured Products</h2>
<section class="item">
        <% @items.each do |item| %>
          <a href="<%= item_path(item) %>">
            <div style="background-color: white; padding: 15px; text-align: center; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); width: 30%;">
            <% if item && item.featured_image.attached? %>
                <%= image_tag item.featured_image, alt: item.name%>
            <% end %>

            <h3><%= item.name %></h3>
            <p>$<%= item.price %></p>
            <p>Rating: <%= item.rating || 0 %></p>
            <p>Available stock: <%= item.inventory_count || 0 %></p>

            <a href="<%= item_path(item) %>" style="padding: 10px; background-color: #FF5722; color: white; text-decoration: none;">View Details</a>
          </div>
          </a>
        <% end %>
    </section>


<!--
<ul>
    <%# <%= debug @items%> 
<% cache @items do%>
<% @items.each do |item|%>
    <div>
        <li>
        <div style= "display: flex; flex-direction: column; gap: 30 px; margin: 40 px;">
            <div><%= link_to item.name, item%> </div>
            <div class="price"> $<%= item.price%> </div>
            <div class="stock"><%= item.inventory_count || 0 %> </div>
        </div>
        </li>
    </div>
<%end%>
<%end%>
</ul>
-->

backend/app/views/items/new.html.erb
<h2> Adding New Item! </h2>

<%= render "form", item: @item%>

backend/app/views/items/show.html.erb
<nav style="display: flex; flex-direction: row; gap: 20px;">
<%= link_to "Back to Main Menu", items_path%>
<%= link_to "Edit Item", edit_item_path(@item.id)%>
<%= button_to "Delete", @item, method: :delete, data: {turbo_confirm: "Are you sure?"}%>
</nav>
<section class = "item">
    <% cache @item do %>
    <%= image_tag @item.featured_image if @item.featured_image.attached?%>
    <section class = "item-info">
        <h1 style = "width: 1200px" ><%= @item.name%></h1>
        <h2>$<%= @item.price%></h2>
        <h3> Rating: <%= @item.rating || 0 %> </h3>
        <h4>Item Description:</h4>
        <h3><%= @item.description %></h3>
        <h4>Stock Available:</h4>
        <h3><%= render "inventory", item: @item%></h3>
    </section>
    <% end %>
</section>