backend/config/routes.rb
Rails.application.routes.draw do

  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable,
  # :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  # devise_for :users
  devise_for :users,  defaults: { format: :json }, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }


  resources :items, only: %i[index show]do
    post 'add_to_cart', to: 'items#add_to_cart'
  end
  root to: "items#index"


  resources :carts, only: %i[index] do
    # resources :cart_items, only: [] do
        patch 'update', on: :member  # Increment or decrement item count
        delete 'remove', on: :member  # Remove item from the cart
    # end
  end
  get 'carts/', to: 'carts#index'
  delete 'carts/', to: 'carts#destroy'
    
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/brand.rb
class Brand < ApplicationRecord
  has_one_attached :logo_image
  validates :name, presence: true
end

backend/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy 
  has_many :items, through: :cart_items

  def get_total_price    
    self.cart_items.reduce(0.0) do |total_price, cart_item| 
      total_price + cart_item.get_subtotal
    end
  end
end

backend/app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :item
    # has_one :item
  
    validates :quantity, numericality: { greater_than_or_equal_to: 1 }
  

    def get_subtotal
      self.item_count * self.item.price
    end
    private

end

backend/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

backend/app/models/item.rb
class Item < ApplicationRecord
  include Notifications

  has_rich_text :description
  has_one_attached :featured_image
  has_many :subscribers, dependent: :destroy
  after_update :update_log

  has_many :cart_items
  has_many :carts, through: :cart_items
  # belongs_to :cart_items, optional: false

  validates :name, presence: true
  validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than: 0 }

  def update_log
    puts "####################################"
    puts "#{self.name} is updated"
    puts "####################################"
  end
end

backend/app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

backend/app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :item
  generates_token_for :unsubscribe
  after_create :log_new_subscriber
  def log_new_subscriber
    puts "###################################\n\tNew subscriber registered\n###################################"
  end
end

backend/app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  has_many :sessions, dependent: :destroy
  has_one :carts, class_name: 'Cart', dependent: :destroy
  after_create :create_user_cart

  normalizes :email, with: ->(e) { e.strip.downcase }
    devise :database_authenticatable, :registerable, :recoverable,:rememberable, :validatable

  private
  def create_user_cart
    ActiveRecord::Base.transaction do
      cart = create_carts!
      puts "#####################################################################################Association between #{self.id} and #{self.carts.id} = #{cart.id}"
    end
  end



end

backend/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  before_action :get_cart
  before_action :get_cart_item, only: %i[update remove]


  def index
    cart_item_info = @cart.cart_items.map do |cart_item|
      {
        id: cart_item.id,
        item: {
          id: cart_item.item.id,
          name: cart_item.item.name,
          price: cart_item.item.price
        },
        subtotal: cart_item.get_subtotal,
        item_count: cart_item.item_count
      }
    end
  
    render json: { data: cart_item_info, total_price: @cart.get_total_price }, status: :ok
  end

  def destroy
    @cart.cart_items.delete_all
    render json: { data: "Cart deleted"}, status: :ok
  end


  def update
    case params[:op]
    when '+'
      @cart_item.increment!(:item_count)

    when '-'
      if @cart_item.item_count > 1
        @cart_item.decrement!(:item_count)
      else
        @cart_item.destroy
      end
    # else
    #   if params[:op].to_i > 0
    #     @cart_item.update!(item_count: params[:op].to_i)
    #   else
    #     render json: { error: 'Item count must be a positive.' }, status: :unprocessable_entity
    #     return
    #   end
    end
    render json: { data: @cart_item }, status: :ok
  end

  def remove
    @cart_item.destroy
    head :no_content
  end


  private

  def get_cart
    @cart = current_user.carts
    render json: { error: 'Cart not found' }, status: :not_found if @cart.nil?
    # puts @cart.cart_items.each{|cart_item| puts cart_item.subtotal}
  end

  def get_cart_item
    @cart_item = @cart.cart_items.find_by(id: params[:id])
    render json: {
      error: 'Cart Item not found'
    }, status: :not_found if @cart_item.nil?
  end
end

backend/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_with_token!, only: %i[add_to_cart]

  before_action :get_item, only: %i[show update destroy]
  before_action :get_item_for_cart, only: %i[add_to_cart]
  before_action :get_cart, only: %i[add_to_cart]

  # GET /items
  def index
    @items = Item.all.order(rating: :desc)
    render json: { data: @items }, status: :ok
  end

  # GET /items/:id
  def show
    render json: { data: @item}, status: :ok
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    if @item.save
      render json: { data: @item }, status: :created
    else
      render json: { errors: @item.errors.messages }, status: :unprocessable_entity
    end
  end

  # PATCH /items/:id
  def update
    if @item.update(item_params)
      render json: { data: @item }, status: :ok
    else
      render json: { errors: @item.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # DELETE /items/:id
  def destroy
    @item.destroy
    head :no_content
  end

  def add_to_cart
    @cart_item = @cart.cart_items.find_by(item_id: @item.id)
    if @cart_item.nil?
      @cart_item = @cart.cart_items.create(item: @item) 
      # @cart_item.subtotal = @cart_item.item_count * @item.price
      # @cart_item.increment!(:item_count)
      # render json: { message: 'Item added to cart', item: @cart_item }, status: :created
    end
    @cart_item.subtotal = @cart_item.item_count * @item.price
    @cart_item.increment!(:item_count)
    render json: { message: "Item added to cart", item: @cart_item }, status: :created
    # else
    #   render json: { message: 'Item already added to cart', item: @cart_item }, status: :created
    # end
  end

  private

  # Strong parameters for creating and updating items
  def item_params
    params.expect(item: %i[ :name ])
  end

  # Find the item by its ID
  
  def get_item
    @item = Item.find_by(id: params[:id] )
    render json: { error: 'Item not found' }, status: :not_found if @item.nil?
  end
  
  def get_item_for_cart
    @item = Item.find_by(id: params[:item_id])
    render json: { error: 'Item not found' }, status: :not_found if @item.nil?
  end

  def get_cart
    # @cart = Cart.find_or_create_by(id: 6)
    puts "$Current user: #{current_user.id}, cart_id : #{current_user.carts}"
    @cart = current_user.carts

    if @cart.nil?
      render json: { error: "Cart not found for user_id: #{current_user.id}" }, status: :not_found 
    end
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/cart_helper.rb
module CartHelper
end

backend/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

backend/app/helpers/cartitem_helper.rb
module CartitemHelper
end

backend/app/helpers/items_helper.rb
module ItemsHelper
end

backend/app/helpers/sessions_helper.rb
module SessionsHelper
end

backend/app/helpers/subscribers_helper.rb
module SubscribersHelper
end

backend/app/helpers/unsubscribe_helper.rb
module UnsubscribeHelper
end

backend/app/helpers/unsubscribes_helper.rb
module UnsubscribesHelper
end

backend/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

backend/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shopping" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body >

    <div>
      <nav >
        <%= link_to "Home", root_path%>
        <%= link_to "Add Product", new_item_path%>
        <%= link_to "Log in" , new_session_path unless authenticated? %>
        <%= button_to "Log out", session_path, method: :delete if authenticated? %>
      </nav>
    </div>
    <div class="notice"><%= notice %></div>
    <div class="header">
       <img src="/shopping_logo.jpg" type="image/jpg" class= "logo">
      <header>
          <h1>Shopping Website!!!</h1>
          <h3> <%= t "welcome"%> </h2>
          <h3> <%= t "hello"%> </h2>
      </header>
    </div>
    <main>
      <%= yield %>
    </main>
  </body>
</html>